version: "3.4"
services:
  ubuntu1604:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/var/work
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro